#!/usr/bin/env bash

st_require_command() {
    if [ ! "$(command -v "${1}")" ]; then
        printf "%s %s\\n" "${1}" "required, but not installed"
        exit 1
    fi
}

st_try_command() {
    if [ ! "$(command -v "${1}")" ]; then
        printf "false"
    else
        printf "true"
    fi
}

st_get_distro() {
    local distro_name="unknown"

    if [ -f /etc/os-release ]; then
        # is systemd
        # shellcheck disable=SC1091
        source /etc/os-release
        distro_name=$( printf "%s" "${NAME}" | awk '{print tolower($0)}' )
    fi

    printf "%s" "${distro_name}"
}

st_get_os() {
    local os_name="unknown"

    os_name=$(uname -s)

    printf "%s" "${os_name}"
}

st_is_os() {
    os_name=$(st_get_os)

    if [ "${1}" = "${os_name}" ]; then
        printf "true"
    else
        printf "false"
    fi
}

st_get_file_encoding() {
    file                \
    --mime-encoding     \
    --brief             \
    "${1}"
}

st_pathmunge () {
    if ! echo "${PATH}" | grep -Eq "(^|:)${1}($|:)" ; then
       if [ "${2}" = "after" ] ; then
          PATH="${PATH}:${1}"
       else
          PATH="${1}:${PATH}"
       fi
    fi
}
